services:
  mongodb:
    build: ./mongodb
    image: vinayraj918/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
  
  catalogue:
    build:
      context: ./catalogue
    image: vinayraj918/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    build: ./mysql
    image: vinayraj918/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop@123
  user:
    build: ./user
    image: vinayraj918/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    build: ./cart
    image: vinayraj918/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: vinayraj918/shipping:v1
    container_name: shipping
    depends_on:
    - mysql 
    - cart 
  payment:
    build: ./payment
    image: vinayraj918/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - cart
    - user
  forntend:
    build: ./frontend
    image: vinayraj918/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
 
networks:
  default:
    name: roboshop
    external: false #true if have created network roboshop in docker
volumes:
  mongodb:
  mysql:
  redis:
  rabbitmq: