FROM node:20.19.5-alpine3.22 AS builder
WORKDIR /opt/server
COPY package*.json .
COPY *.js .
# this may add extra cache memeory
RUN npm install


FROM node:20.19.5-alpine3.22
WORKDIR /opt/server
RUN addgroup -S roboshop && adduser -S roboshop -G robosho && \
    chown -R roboshop:roboshop /opt/server
EXPOSE 8080
LABEL com.project="roboshop" \
     component="catalogue" \
     created_by="Vinayraj"
ENV MONGO="true" \
    MONGO_URL="mongodb://mongodb:27017/catalogue"
COPY --from=builder -chown=roboshop /opt/server/opt/server
USER roboshop
CMD ["server.js"]
ENTRYPOINT ["node"]


#FROM node:20
#WORKDIR /opt/server
#COPY package*.json .
#COPY *.js .
#RUN npm install
#ENV MONGO="true" \
    #MONGO_URL="mongodb://mongodb:27017/catalogue"
#CMD ["node", "server.js"]
    