FROM node:20.19.5-alpine3.22 AS builder
WORKDIR /opt/server
COPY package*.json .
COPY *.js .
# this may add extra cache memeory
RUN npm install


FROM node:20.19.5-alpine3.22
# create a group and user
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
WORKDIR /opt/server
COPY --from=builder /opt/server /opt/server
ENV MONGO="true" \
    MONGO_URL="mongodb://mongodb:27017/catalogue"
RUN chown -R roboshop:roboshop /opt/server
USER roboshop
CMD ["server.js"]
ENTRYPOINT [ "node " ]


#FROM node:20
#WORKDIR /opt/server
#COPY package*.json .
#COPY *.js .
#RUN npm install
#ENV MONGO="true" \
    #MONGO_URL="mongodb://mongodb:27017/catalogue"
#CMD ["node", "server.js"]
    